name: my_click_doctor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  custom_pop_up_menu: ^1.2.3+1
  dropdown_button2: ^1.4.0
  awesome_dialog: ^3.0.0
  popup_card: ^0.1.0
  rflutter_alert: ^2.0.4
  file_picker: ^5.0.1
  video_player: ^2.4.7
  webview_flutter: ^3.0.4
  zoom_widget: ^0.2.1
  camera: ^0.10.0+1
  intl: ^0.17.0
  permission_handler: ^10.0.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  form_field_validator: ^1.1.0
  flutter_secure_storage: ^6.0.0
  provider: ^6.0.4
  carousel_slider: ^4.1.1
  gallery_saver: ^2.3.2
  flutter_datetime_picker: ^1.5.1
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/footer-logo.png
    - assets/logo.png
    - assets/login-bg.png
    - assets/question-sign.png
    - assets/female-user.png
    - assets/green-join-call.png
    - assets/category-(2).png
    - assets/four-dots.png
    - assets/info.png
    - assets/calendar.png
    - assets/info1.png
    - assets/bookmark.png
    - assets/doctor-pic.png
    - assets/stethoscope.png
    - assets/book.png
    - assets/repeat.png
    - assets/cancel.png
    - assets/calendar-dark-green.png
    - assets/chat-1.png
    - assets/profile-2.png
    - assets/file-upload1.png
    - assets/bg.png
    - assets/word.png
    - assets/pdf.png
    - assets/image.png
    - assets/green-phone.png
    - assets/male-user.png
    - assets/send.png
    - assets/alert.png
    - assets/logout.png
    - assets/profile.png
    - assets/check.png
    - assets/help.png
    - assets/forget-password.png
    - assets/m_icon_color.png
    - assets/m_icon.png
    - assets/splash.png
    - assets/micon.png
    - assets/delete.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
